/// <reference path="./index.d.ts" />

export const Actions: Infrastructure.Actions = {
  ADD_OPEN_DOCUMENT_RQ: "ADD_OPEN_DOCUMENT_RQ",
  REMOVE_OPEN_DOCUMENT_RQ: "REMOVE_OPEN_DOCUMENT_RQ",
  OPEN_DOCUMENTS_CHANGED_RS: "OPEN_DOCUMENTS_CHANGED_RS", //THIS RESPONSE MAPS TO ADD/REMOVE DOCUMENT REQUESTS
  // TO MANAGE IState.availableDocuments
  SET_AVAILABLE_DOCUMENTS_RQ: "SET_AVAILABLE_DOCUMENTS_RQ",
  SET_AVAILABLE_DOCUMENTS_RS: "SET_AVAILABLE_DOCUMENTS_RS",
  // TO MANAGE  IState.currentDocument
  SET_CURRENT_DOCUMENT_RQ: "SET_CURRENT_DOCUMENT_RQ",
  SET_CURRENT_DOCUMENT_RS: "SET_CURRENT_DOCUMENT_RS"
};
